-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.eventos
(
    id serial NOT NULL,
    event_id character varying COLLATE pg_catalog."default",
    "timestamp" timestamp without time zone,
    event_type character varying(100) COLLATE pg_catalog."default",
    result character varying(100) COLLATE pg_catalog."default",
    cause_code character varying(200) COLLATE pg_catalog."default",
    imsi character varying(300) COLLATE pg_catalog."default",
    cell_id character varying(200) COLLATE pg_catalog."default",
    mme_id character varying(10) COLLATE pg_catalog."default",
    tracking_area character varying(100) COLLATE pg_catalog."default",
    duration_ms character varying(100) COLLATE pg_catalog."default",
    rat_type character varying(100) COLLATE pg_catalog."default",
    apn character varying(100) COLLATE pg_catalog."default",
    plmn_id character varying(100) COLLATE pg_catalog."default",
    enodeb_id character varying(100) COLLATE pg_catalog."default",
    CONSTRAINT eventos_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.events
(
    event_id double precision,
    "timestamp" timestamp without time zone,
    event_type text COLLATE pg_catalog."default",
    result text COLLATE pg_catalog."default",
    failure_cause text COLLATE pg_catalog."default",
    imsi_hash text COLLATE pg_catalog."default",
    imei_hash text COLLATE pg_catalog."default",
    cell_id text COLLATE pg_catalog."default",
    enodeb_id text COLLATE pg_catalog."default",
    mme_id text COLLATE pg_catalog."default",
    tracking_area text COLLATE pg_catalog."default",
    duration_ms bigint,
    rat_type text COLLATE pg_catalog."default",
    frequency_band text COLLATE pg_catalog."default"
);
END;